import React, { createContext, useContext, useState, ReactNode } from 'react';
import { productTranslations } from '@/data/translations/products';
import { commonTranslations } from '@/data/translations/common';

type Language = 'es' | 'en' | 'fr' | 'de' | 'pt' | 'hi' | 'zh';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const translations: Record<Language, Record<string, string>> = {
  es: {
    // Navigation
    home: 'Inicio',
    shop: 'Tienda',
    audio: 'Audio Premium',
    account: 'Cuenta',
    cart: 'Carrito',
    login: 'Iniciar Sesión',
    register: 'Registrarse',
    logout: 'Cerrar Sesión',
    
    // Home Page
    heroTitle: 'V&M Candle Experience',
    heroSubtitle: 'Rituales que Restauran tu Alma',
    heroDescription: 'Velas artesanales de alta gama, formuladas con ceras vegetales, aceites esenciales puros y fragancias de grado perfumista.',
    shopNow: 'Comprar Ahora',
    subscribe: 'Suscribirse',
    exploreAudio: 'Explorar Audio Premium',
    featuredProductsDesc: 'Velas artesanales de alta gama, diseñadas como rituales de bienestar',
    audioSectionTitle: 'Experiencia de Audio Premium',
    audioSectionDesc: 'Complementa tu ritual con contenido de audio exclusivo: meditaciones guiadas, música ambiental y frecuencias de sanación diseñadas para profundizar tu experiencia sensorial.',
    
    // Products
    products: 'Productos',
    addToCart: 'Añadir al Carrito',
    viewDetails: 'Ver Detalles',
    price: 'Precio',
    inStock: 'En Stock',
    outOfStock: 'Agotado',
    
    // Individual Products - Spanish
    vanillaSerenityName: 'Serenidad Vainilla',
    vanillaSerenityDescription: 'Una lujosa vela de vainilla cremosa para confort cálido y tranquilidad suave',
    lavenderDreamsName: 'Sueños de Lavanda',
    lavenderDreamsDescription: 'Lavanda francesa calmante mezclada con notas florales delicadas para relajación profunda',
    sandalwoodMystiqueName: 'Místico Sándalo',
    sandalwoodMystiqueDescription: 'Sándalo rico y terroso con notas amaderadas cálidas para enraizamiento y meditación',
    roseGardenName: 'Jardín de Rosas',
    roseGardenDescription: 'Pétalos de rosa elegantes con un toque de jazmín para un ambiente romántico y refinado',
    citrusBlissName: 'Dicha Cítrica',
    citrusBlissDescription: 'Mezcla vibrante de naranja, limón y pomelo para energía refrescante',
    eucalyptusMintName: 'Eucalipto Menta',
    eucalyptusMintDescription: 'Eucalipto fresco con menta para claridad mental y revitalización de los sentidos',
    jasmineName: 'Jazmín Nocturno',
    jasmineDescription: 'Jazmín exótico con notas verdes sutiles para equilibrio emocional y sensualidad',
    cedarwoodName: 'Cedro Majestuoso',
    cedarwoodDescription: 'Cedro terroso con toques amaderados ahumados para fuerza y estabilidad',
    amberName: 'Ámbar Dorado',
    amberDescription: 'Ámbar cálido con vainilla y almizcle para lujo sensual y reconfortante',
    bergamotName: 'Bergamota Brillante',
    bergamotDescription: 'Bergamota efervescente con té earl grey para elevación del ánimo y claridad',
    peonyName: 'Peonía Elegante',
    peonyDescription: 'Peonía delicada con rosa y fresia para feminidad suave y elegante',
    
    // Collections
    productCalmRitual: 'Calm Ritual',
    productCalmRitualDesc: 'Seis esencias que restauran tu alma',
    productPremiumCollection: 'Premium Collection',
    productPremiumCollectionDesc: 'Set completo de experiencia ritual',
    productMeditationEssence: 'Meditation Essence',
    productMeditationEssenceDesc: 'Calma profunda y armonía interior',
    productSpiritualConnection: 'Spiritual Connection',
    productSpiritualConnectionDesc: 'Expande tu conciencia',
    productEmotionalBalance: 'Emotional Balance',
    productEmotionalBalanceDesc: 'Restaura tu bienestar emocional',
    productInnerStrength: 'Inner Strength',
    productInnerStrengthDesc: 'Estabilidad energética y arraigo',
    productLongDesc: 'En V&M creamos velas artesanales de alta gama, formuladas con ceras vegetales, aceites esenciales puros y fragancias de grado perfumista que elevan los sentidos. Cada esencia ha sido diseñada como un ritual de bienestar: calma, claridad, presencia y expansión interior en una sola experiencia olfativa.',
    productFeature1: 'Calma Profunda & Armonía Interior',
    productFeature2: 'Elevación del Ánimo & Bienestar Emocional',
    productFeature3: 'Conexión Espiritual & Presencia Plena',
    productFeature4: 'Relajación Emocional & Contención Suave',
    productFeature5: 'Fortaleza Interior & Estabilidad Energética',
    productFeature6: 'Confort Sensorial & Calidez Afectiva',
    burnTime: 'Tiempo de Combustión',
    size: 'Tamaño',
    features: 'Características',
    backToShop: 'Volver a la tienda',
    productNotFound: 'Producto no encontrado',
    shopDescription: 'Descubre nuestra colección completa de velas artesanales y experiencias premium',
    allCategories: 'Todas las Categorías',
    categoryCandles: 'Velas Individuales',
    categorySets: 'Sets Premium',
    sortPopular: 'Más Populares',
    sortPriceLow: 'Precio: Menor a Mayor',
    sortPriceHigh: 'Precio: Mayor a Menor',
    
    // Cart & Checkout
    yourCart: 'Tu Carrito',
    subtotal: 'Subtotal',
    shipping: 'Envío',
    freeShipping: 'Envío Gratis',
    total: 'Total',
    checkout: 'Finalizar Compra',
    continueShopping: 'Continuar Comprando',
    emptyCart: 'Tu carrito está vacío',
    quantity: 'Cantidad',
    remove: 'Eliminar',
    contactInformation: 'Información de Contacto',
    firstName: 'Nombre',
    lastName: 'Apellido',
    phone: 'Teléfono',
    shippingAddress: 'Dirección de Envío',
    address: 'Dirección',
    city: 'Ciudad',
    postalCode: 'Código Postal',
    country: 'País',
    paymentMethod: 'Método de Pago',
    paymentWebpay: 'Pago con Webpay',
    paymentWebpayDesc: 'Pago seguro con tarjeta de crédito o débito',
    placeOrder: 'Realizar Pedido',
    processing: 'Procesando...',
    orderSummary: 'Resumen del Pedido',
    orderConfirmed: '¡Pedido confirmado!',
    orderConfirmedDesc: 'Recibirás un email de confirmación pronto.',
    
    // Account
    myAccount: 'Mi Cuenta',
    orderHistory: 'Historial de Pedidos',
    quickBuy: 'Compra Rápida',
    subscription: 'Suscripción',
    profile: 'Perfil',
    editProfile: 'Editar Perfil',
    subscriptionActive: 'Plan Activo',
    nextRenewal: 'Próxima renovación',
    manageSubscription: 'Gestionar Suscripción',
    noSubscription: 'No tienes una suscripción activa',
    orderDate: 'Fecha',
    orderTotal: 'Total',
    orderStatus: 'Estado',
    delivered: 'Entregado',
    reorder: 'Volver a Pedir',
    
    // Audio Experience
    audioExperience: 'Experiencia de Audio',
    premiumContent: 'Contenido Premium',
    unlockAccess: 'Desbloquear Acceso',
    subscriptionPlans: 'Planes de Suscripción',
    monthly: 'Mensual',
    quarterly: 'Trimestral',
    yearly: 'Anual',
    audioDescription: 'Complementa tu ritual de vela con experiencias de audio diseñadas para profundizar tu bienestar. Cada pista ha sido cuidadosamente creada para elevar tu práctica de meditación y relajación.',
    ambientMusic: 'Música Ambiental',
    guidedMeditations: 'Meditaciones Guiadas',
    healingFrequencies: 'Frecuencias Sanadoras',
    exclusiveContent: 'Contenido Exclusivo',
    freePreview: 'Vista Previa Gratuita',
    freePreviewDesc: 'Escucha muestras de nuestras pistas más populares',
    deepCalm: 'Calma Profunda',
    spiritualConnection: 'Conexión Espiritual',
    emotionalBalance: 'Equilibrio Emocional',
    previewSample: 'Muestra de 2 minutos',
    listenPreview: 'Escuchar Vista Previa',
    chooseYourPlan: 'Elige tu Plan',
    planMonthly: 'Mensual',
    planQuarterly: 'Trimestral',
    planYearly: 'Anual',
    perMonth: '/ mes',
    per3Months: '/ 3 meses',
    perYear: '/ año',
    save: 'Ahorra',
    mostPopular: 'Más Popular',
    selectPlan: 'Seleccionar Plan',
    planFeature1: 'Acceso completo a la biblioteca de audio',
    planFeature2: 'Meditaciones guiadas semanales',
    planFeature3: 'Música ambiental premium',
    planFeature4: 'Frecuencias de sanación',
    planFeature5: 'Todos los beneficios del plan mensual',
    planFeature6: 'Contenido exclusivo trimestral',
    planFeature7: 'Sesiones de meditación extendidas',
    planFeature8: 'Playlist personalizados',
    planFeature9: 'Todos los beneficios anteriores',
    planFeature10: 'Acceso a masterclasses exclusivas',
    planFeature11: 'Descuentos en productos V&M',
    planFeature12: 'Contenido anticipado',
    uniqueKeyAccess: 'Acceso con Clave Única',
    uniqueKeyAccessDesc: 'Ingresa tu clave de acceso única para desbloquear el contenido premium',
    enterAccessKey: 'Ingresa tu clave de acceso',
    unlock: 'Desbloquear',
    invalidKey: 'Clave inválida',
    
    // Newsletter
    newsletter: 'Boletín',
    subscribeNewsletter: 'Suscríbete a nuestro boletín',
    newsletterDesc: 'Recibe contenido exclusivo, lanzamientos y ofertas especiales',
    email: 'Correo Electrónico',
    send: 'Enviar',
    subscribing: 'Suscribiendo...',
    subscribed: '¡Suscrito!',
    subscribedDesc: 'Gracias por suscribirte a nuestro boletín.',
    
    // Auth
    welcomeBack: 'Bienvenido de Nuevo',
    loginDesc: 'Inicia sesión para acceder a tu cuenta',
    password: 'Contraseña',
    rememberMe: 'Recordarme',
    forgotPassword: '¿Olvidaste tu contraseña?',
    noAccount: '¿No tienes cuenta?',
    createAccount: 'Crear Cuenta',
    createAccountDesc: 'Únete a la familia V&M',
    confirmPassword: 'Confirmar Contraseña',
    hasAccount: '¿Ya tienes cuenta?',
    
    // Common
    loading: 'Cargando...',
    search: 'Buscar',
    filter: 'Filtrar',
    sort: 'Ordenar',
    cancel: 'Cancelar',
    delete: 'Eliminar',
    edit: 'Editar',
    hours: 'horas',
    back: 'Volver',
    free: 'Gratis',
    freeShippingOver100: '¡Envío gratis en compras sobre $100!',
    quantityLabel: 'Cantidad',

    // Footer - Information Section
    information: 'Información',
    contact: 'Contacto',
    technicalSheet: 'Ficha Técnica',
    termsOfUse: 'Condiciones de Uso',
    privacyPolicy: 'Política de Privacidad',

    // Subscription Page
    premiumAudioExperience: 'Experiencia de Audio Premium',
    subscriptionHeaderDesc: 'Desbloquea acceso ilimitado a nuestra biblioteca de audio exclusiva con meditaciones guiadas, paisajes sonoros ambientales y experiencias de relajación.',
    activeSubscription: 'Tienes una suscripción activa',
    manageSubscriptionLink: 'Gestionar suscripción',
    bestValue: 'Mejor Valor',
    perPeriod: 'por',
    frequentlyAskedQuestions: 'Preguntas Frecuentes',
    faqCancelTitle: '¿Puedo cancelar en cualquier momento?',
    faqCancelAnswer: 'Sí! Puedes cancelar tu suscripción en cualquier momento desde la configuración de tu cuenta. Continuarás teniendo acceso hasta el final de tu período de facturación actual.',
    faqChangePlanTitle: '¿Puedo cambiar mi plan?',
    faqChangePlanAnswer: 'Absolutamente. Puedes actualizar o bajar de categoría tu plan en cualquier momento desde la configuración de tu cuenta. Los cambios entrarán en vigor en tu próximo ciclo de facturación.',
    faqPaymentTitle: '¿Qué métodos de pago aceptan?',
    faqPaymentAnswer: 'Aceptamos todas las tarjetas de crédito y débito principales a través de Transbank WebPay Plus, la plataforma de pago más confiable de Chile.',
    faqTrialTitle: '¿Hay una prueba gratuita?',
    faqTrialAnswer: 'Actualmente, no ofrecemos una prueba gratuita, pero puedes obtener una vista previa de experiencias de audio seleccionadas en nuestras páginas de productos antes de suscribirte.',

    // Subscription Legal Acceptance
    beforeSubscribe: 'Antes de suscribirse, por favor lea y acepte:',
    acceptTerms: 'He leído y acepto las',
    acceptTermsSuffix: 'del sistema de suscripción.',
    acceptPrivacy: 'He leído y acepto la',
    acceptPrivacySuffix: 'de V&M Candle Experience.',
    mustAcceptBoth: '* Debe aceptar ambos documentos para poder suscribirse.',
    canProceed: 'Puede proceder con la suscripción.',
    acceptTermsButton: 'Acepte los términos',
    mustAcceptConditions: 'Debe aceptar las condiciones arriba',
    alreadySubscribed: 'Ya suscrito',
    subscribeNow: 'Suscribirse',
    processingPayment: 'Procesando...',

    // Product Documentation Page
    productDocumentation: 'Documentación del Producto',
    productDocumentationDesc: 'Información técnica y de seguridad de nuestros productos V&M Candle Experience. Transparencia y calidad en cada detalle.',
    technicalDataSheet: 'Ficha Técnica Oficial',
    safetyDataSheet: 'Hoja de Seguridad – MSDS',
    safetyDataSheetSubtitle: 'Material Safety Data Sheet',
    issuedDate: 'Fecha de emisión',

    // Technical Sheet Sections
    productIdentification: 'Identificación del Producto',
    productName: 'Nombre del Producto',
    brand: 'Marca',
    productType: 'Tipo de Producto',
    composition: 'Composición',
    naturalSoyWax: 'Cera de Soya Natural',
    waxAmount: 'Cantidad de Cera',
    essentialOil: 'Aceite Esencial',
    totalWeight: 'Peso Total',
    aromaticLoad: 'Carga Aromática',
    concentrationPercentage: 'Porcentaje de concentración',
    highPerfumery: 'Alta Perfumería – Edición Premium',
    curingTime: 'Tiempo de Curado',
    minimumRecommended: 'Mínimo Recomendado',
    optimalLuxury: 'Óptimo Nivel Lujo',
    days: 'días',
    wickType: 'Tipo de Mecha',
    cottonWick: 'Mecha de algodón 100% natural',
    usageInstructions: 'Modo de Uso',
    usageStep1: 'Encender la vela sobre una superficie estable y resistente al calor.',
    usageStep2: 'Aromatizar el lugar mínimo por 45 minutos.',
    usageStep3: 'No dejar encendida por más de 2 a 3 horas continuas.',
    keepAwayFromChildren: 'Mantener fuera del alcance de niños y mascotas.',
    safetyWarnings: 'Advertencias de Seguridad',
    noFlammableMaterials: 'No utilizar cerca de materiales inflamables',
    noMoveWhileLit: 'No mover la vela mientras esté encendida',
    keepDistance: 'Mantener 10 cm mínimo entre velas encendidas',
    productClassification: 'Clasificación del Producto',
    classificationDesc: 'Producto aromático premium de uso ambiental.',
    notMedicine: 'No es un medicamento.',
    manufacturing: 'Fabricación',
    manufacturingDesc: 'Producto elaborado a mano en pequeños lotes bajo estándares artesanales de alta calidad.',
    signatureLuxuryNote: 'Por su alta concentración aromática, este producto pertenece a la línea Signature Luxury de V&M Candle Experience y está destinado a uso ritual, ceremonial o de alta perfumería.',

    // MSDS Sections
    hazardIdentification: 'Identificación de Peligros',
    flammableProduct: 'Producto inflamable',
    burnRisk: 'Riesgo de quemaduras por cera caliente',
    nonToxicNormal: 'No toxicológico en condiciones normales de uso',
    compositionInfo: 'Composición / Información sobre Componentes',
    vegetableSoyWax: 'Cera vegetal de soya',
    naturalFragrances: 'Fragancias naturales',
    leadFreeCottonWick: 'Mecha de algodón sin plomo',
    firstAid: 'Medidas de Primeros Auxilios',
    skinContact: 'Contacto con la piel:',
    coolWithWater: 'Enfriar con agua fría.',
    fireFighting: 'Medidas de Lucha contra Incendios',
    useClassBExtinguisher: 'Utilizar extintores clase B',
    neverUseWater: 'Nunca usar agua directamente sobre la cera encendida',
    spillMeasures: 'Medidas en Caso de Derrame Accidental',
    letSolidify: 'Dejar solidificar la cera antes de limpiar',
    avoidBurns: 'Evitar quemaduras',
    handlingStorage: 'Manipulación y Almacenamiento',
    keepFromHeat: 'Mantener lejos del calor intenso',
    storeCoolDry: 'Almacenar en lugar fresco y seco',
    exposureControl: 'Control de Exposición / Protección Personal',
    noSpecialProtection: 'No requiere protección especial en uso normal.',
    physicalProperties: 'Propiedades Físicas y Químicas',
    state: 'Estado',
    solid: 'Sólido',
    color: 'Color',
    variable: 'Variable',
    smell: 'Olor',
    aromatic: 'Aromático',
    stabilityReactivity: 'Estabilidad y Reactividad',
    stableProduct: 'Producto estable bajo condiciones normales',
    avoidDirectFire: 'Evitar exposición a fuego directo',
    toxicologicalInfo: 'Información Toxicológica',
    nonToxic: 'No tóxico',
    doNotIngest: 'No ingerir',
    ecologicalInfo: 'Información Ecológica',
    biodegradable: 'Producto biodegradable',
    recyclablePackaging: 'Envase reciclable',
    disposalInfo: 'Consideraciones sobre Eliminación',
    disposeLocally: 'Eliminar conforme a normativa local',
    noDrainDisposal: 'No verter en desagües',
    transportInfo: 'Información sobre Transporte',
    notDangerous: 'No considerado material peligroso para transporte terrestre.',
    regulatoryInfo: 'Información Reglamentaria',
    chileanCompliance: 'Producto conforme a normativas chilenas vigentes para objetos decorativos.',
    otherInfo: 'Otra Información',
    infoDisclaimer: 'Este documento ha sido elaborado para uso informativo y de seguridad preventiva.',
    emergencyPhone: 'Emergencia',
    contactQuestions: 'Para consultas adicionales, contacte a',

    // Terms of Use Page
    termsTitle: 'CONDICIONES DE USO – SISTEMA DE SUSCRIPCIÓN',
    termsLastUpdate: 'Última actualización',
    termsIntro: 'Al contratar una suscripción en V&M Candle Experience, el usuario acepta plenamente las siguientes Condiciones de Uso:',
    termsSection1Title: '1. OBJETO DEL SERVICIO',
    termsSection1Content: 'La suscripción otorga acceso a contenidos digitales, programas, sesiones, material educativo, audios, videos, cursos, mentorías u otros servicios ofrecidos en la plataforma, según el plan contratado.',
    termsSection2Title: '2. NATURALEZA DEL SERVICIO',
    termsSection2Content: 'Todos los contenidos ofrecidos tienen carácter educativo, formativo, terapéutico complementario y de desarrollo personal, y NO sustituyen tratamientos médicos, psicológicos o psiquiátricos.',
    termsSection2Note: 'El usuario es plenamente responsable del uso que haga de la información entregada.',
    termsSection3Title: '3. MODALIDAD DE PAGO',
    termsSection4Title: '4. POLÍTICA DE NO REEMBOLSO',
    termsSection4Intro: 'Una vez realizado el pago de la suscripción:',
    termsSection4NoRefund: 'NO se realizan devoluciones, totales ni parciales.',
    termsSection4Cancel: 'El usuario puede cancelar su suscripción para evitar futuros cobros, pero no se reembolsa el período ya pagado.',
    termsSection5Title: '5. CANCELACIÓN',
    termsSection5Intro: 'El usuario puede cancelar su suscripción en cualquier momento desde su cuenta o solicitándolo por correo a:',
    termsSection5Effect: 'La cancelación:',
    termsSection5Stop: 'Detiene futuros cobros.',
    termsSection5Access: 'Mantiene el acceso activo hasta la fecha de término del período ya pagado.',
    termsSection6Title: '6. ACCESO Y USO DE CUENTA',
    termsSection7Title: '7. PROPIEDAD INTELECTUAL',
    termsSection7Content: 'Todos los contenidos de la plataforma son propiedad exclusiva de V&M Candle Experience.',
    termsSection7Forbidden: 'Está estrictamente prohibido:',
    termsSection7Auth: 'sin autorización expresa por escrito.',
    termsSection8Title: '8. MODIFICACIONES DEL SERVICIO',
    termsSection8Intro: 'La plataforma se reserva el derecho de:',
    termsSection8Note: 'sin afectar al usuario negativamente en su acceso contratado.',
    termsSection9Title: '9. RESPONSABILIDAD DEL USUARIO',
    termsSection9Intro: 'El usuario declara que:',
    termsSection10Title: '10. SUSPENSIÓN O TÉRMINO DEL SERVICIO',
    termsSection10Intro: 'Nos reservamos el derecho de suspender una cuenta si el usuario:',
    termsSection11Title: '11. PROTECCIÓN DE DATOS',
    termsSection11Content: 'Los datos del usuario serán tratados con estricta confidencialidad y conforme a la legislación vigente de protección de datos.',
    termsSection12Title: '12. JURISDICCIÓN',
    termsSection12Content: 'Estas condiciones se rigen por las leyes de la República de Chile. Cualquier conflicto será resuelto en los tribunales competentes de Santiago.',
    termsSection13Title: '13. ACEPTACIÓN',
    termsSection13Content: 'Al suscribirse, el usuario declara haber leído, comprendido y aceptado íntegramente estas Condiciones de Uso.',

    // Privacy Policy Page
    privacyTitle: 'POLÍTICA DE PRIVACIDAD',
    privacyIntro: 'En V&M Candle Experience, respetamos y protegemos la privacidad de todos nuestros usuarios. Esta Política de Privacidad describe cómo recopilamos, utilizamos y protegemos tus datos personales.',
    privacyAcceptance: 'Al utilizar nuestros servicios, aceptas las prácticas descritas a continuación.',
    privacySection1Title: '1. RESPONSABLE DEL TRATAMIENTO DE DATOS',
    privacySection1Intro: 'El responsable del tratamiento de los datos es:',
    privacyName: 'Nombre',
    privacyBrand: 'Marca comercial',
    privacyContact: 'Correo de contacto',
    privacyCountry: 'País',
    privacySection2Title: '2. DATOS PERSONALES QUE RECOPILAMOS',
    privacySection2Intro: 'Podemos recopilar los siguientes datos:',
    privacySection2Note: 'Nunca solicitamos datos sensibles innecesarios.',
    privacySection3Title: '3. FINALIDAD DEL USO DE LOS DATOS',
    privacySection3Intro: 'Tus datos personales se utilizan para:',
    privacySection4Title: '4. CONFIDENCIALIDAD Y SEGURIDAD',
    privacySection4Content: 'Tus datos son almacenados bajo estrictas medidas de seguridad y confidencialidad. Implementamos protocolos tecnológicos y administrativos para evitar accesos no autorizados, pérdida o alteración de la información.',
    privacySection5Title: '5. USO DE PLATAFORMAS DE PAGO Y TERCEROS',
    privacySection5Intro: 'Nuestros pagos pueden ser procesados a través de plataformas externas como:',
    privacySection5Note: 'Estas plataformas cuentan con sus propias políticas de privacidad y manejo de datos.',
    privacySection6Title: '6. USO DE COOKIES',
    privacySection6Intro: 'Nuestro sitio puede utilizar cookies para:',
    privacySection6Note: 'El usuario puede configurar su navegador para rechazar las cookies si así lo desea.',
    privacySection7Title: '7. DERECHOS DEL USUARIO',
    privacySection7Intro: 'El usuario tiene derecho a:',
    privacySection7Contact: 'Para ejercer estos derechos, puede escribir a:',
    privacySection8Title: '8. CONSERVACIÓN DE LOS DATOS',
    privacySection8Content: 'Los datos se conservarán por el tiempo necesario para cumplir los fines para los que fueron recopilados o por obligación legal.',
    privacySection9Title: '9. MENORES DE EDAD',
    privacySection9Content: 'Nuestros servicios no están dirigidos a menores de 18 años. Si detectamos el uso por parte de un menor sin autorización, los datos serán eliminados inmediatamente.',
    privacySection10Title: '10. MODIFICACIONES A ESTA POLÍTICA',
    privacySection10Content: 'Nos reservamos el derecho de modificar esta Política de Privacidad en cualquier momento. Los cambios serán publicados en esta misma sección.',
    privacySection11Title: '11. ACEPTACIÓN',
    privacySection11Content: 'El uso de la plataforma implica la aceptación expresa de esta Política de Privacidad.',
    privacySection12Title: '12. LEGISLACIÓN APLICABLE',
    privacySection12Content: 'Esta política se rige por la legislación vigente de la República de Chile, especialmente la Ley N° 19.628 sobre protección de datos personales.',
  },
  en: {
    home: 'Home',
    shop: 'Shop',
    audio: 'Premium Audio',
    account: 'Account',
    cart: 'Cart',
    login: 'Login',
    register: 'Register',
    logout: 'Logout',
    
    heroTitle: 'V&M Candle Experience',
    heroSubtitle: 'Rituals that Restore your Soul',
    heroDescription: 'High-end artisan candles, formulated with plant-based waxes, pure essential oils, and perfume-grade fragrances.',
    shopNow: 'Shop Now',
    subscribe: 'Subscribe',
    exploreAudio: 'Explore Premium Audio',
    featuredProductsDesc: 'High-end artisan candles designed as wellness rituals',
    audioSectionTitle: 'Premium Audio Experience',
    audioSectionDesc: 'Complement your ritual with exclusive audio content: guided meditations, ambient music, and healing frequencies designed to deepen your sensory experience.',
    
    products: 'Products',
    addToCart: 'Add to Cart',
    viewDetails: 'View Details',
    price: 'Price',
    inStock: 'In Stock',
    outOfStock: 'Out of Stock',
    
    // Individual Products - English
    vanillaSerenityName: 'Vanilla Serenity',
    vanillaSerenityDescription: 'A luxurious creamy vanilla candle for warm comfort and gentle tranquility',
    lavenderDreamsName: 'Lavender Dreams',
    lavenderDreamsDescription: 'Soothing French lavender blended with delicate floral notes for deep relaxation',
    sandalwoodMystiqueName: 'Sandalwood Mystique',
    sandalwoodMystiqueDescription: 'Rich, earthy sandalwood with warm woody notes for grounding and meditation',
    roseGardenName: 'Rose Garden',
    roseGardenDescription: 'Elegant rose petals with a hint of jasmine for romantic and refined ambiance',
    citrusBlissName: 'Citrus Bliss',
    citrusBlissDescription: 'Vibrant blend of orange, lemon, and grapefruit for refreshing energy',
    eucalyptusMintName: 'Eucalyptus Mint',
    eucalyptusMintDescription: 'Fresh eucalyptus with peppermint for mental clarity and sense invigoration',
    jasmineName: 'Night Jasmine',
    jasmineDescription: 'Exotic jasmine with subtle green notes for emotional balance and sensuality',
    cedarwoodName: 'Majestic Cedarwood',
    cedarwoodDescription: 'Earthy cedar with smoky woody touches for strength and stability',
    amberName: 'Golden Amber',
    amberDescription: 'Warm amber with vanilla and musk for sensual, comforting luxury',
    bergamotName: 'Bright Bergamot',
    bergamotDescription: 'Sparkling bergamot with earl grey tea for mood elevation and clarity',
    peonyName: 'Elegant Peony',
    peonyDescription: 'Delicate peony with rose and freesia for gentle, elegant femininity',
    
    // Collections
    productCalmRitual: 'Calm Ritual',
    productCalmRitualDesc: 'Six essences that restore your soul',
    productPremiumCollection: 'Premium Collection',
    productPremiumCollectionDesc: 'Complete ritual experience set',
    productMeditationEssence: 'Meditation Essence',
    productMeditationEssenceDesc: 'Deep calm and inner harmony',
    productSpiritualConnection: 'Spiritual Connection',
    productSpiritualConnectionDesc: 'Expand your consciousness',
    productEmotionalBalance: 'Emotional Balance',
    productEmotionalBalanceDesc: 'Restore emotional wellbeing',
    productInnerStrength: 'Inner Strength',
    productInnerStrengthDesc: 'Energetic stability and grounding',
    productLongDesc: 'At V&M we create high-end artisan candles, formulated with plant-based waxes, pure essential oils, and perfume-grade fragrances that elevate the senses. Each essence has been designed as a wellness ritual: calm, clarity, presence, and inner expansion in a single olfactory experience.',
    productFeature1: 'Deep Calm & Inner Harmony',
    productFeature2: 'Mood Elevation & Emotional Wellbeing',
    productFeature3: 'Spiritual Connection & Full Presence',
    productFeature4: 'Emotional Relaxation & Gentle Support',
    productFeature5: 'Inner Strength & Energetic Stability',
    productFeature6: 'Sensory Comfort & Affective Warmth',
    burnTime: 'Burn Time',
    size: 'Size',
    features: 'Features',
    backToShop: 'Back to shop',
    productNotFound: 'Product not found',
    shopDescription: 'Discover our complete collection of artisan candles and premium experiences',
    allCategories: 'All Categories',
    categoryCandles: 'Individual Candles',
    categorySets: 'Premium Sets',
    sortPopular: 'Most Popular',
    sortPriceLow: 'Price: Low to High',
    sortPriceHigh: 'Price: High to Low',
    
    yourCart: 'Your Cart',
    subtotal: 'Subtotal',
    shipping: 'Shipping',
    freeShipping: 'Free Shipping',
    total: 'Total',
    checkout: 'Checkout',
    continueShopping: 'Continue Shopping',
    emptyCart: 'Your cart is empty',
    quantity: 'Quantity',
    remove: 'Remove',
    contactInformation: 'Contact Information',
    firstName: 'First Name',
    lastName: 'Last Name',
    phone: 'Phone',
    shippingAddress: 'Shipping Address',
    address: 'Address',
    city: 'City',
    postalCode: 'Postal Code',
    country: 'Country',
    paymentMethod: 'Payment Method',
    paymentWebpay: 'Webpay Payment',
    paymentWebpayDesc: 'Secure payment with credit or debit card',
    placeOrder: 'Place Order',
    processing: 'Processing...',
    orderSummary: 'Order Summary',
    orderConfirmed: 'Order confirmed!',
    orderConfirmedDesc: 'You will receive a confirmation email soon.',
    
    myAccount: 'My Account',
    orderHistory: 'Order History',
    quickBuy: 'Quick Buy',
    subscription: 'Subscription',
    profile: 'Profile',
    editProfile: 'Edit Profile',
    subscriptionActive: 'Active Plan',
    nextRenewal: 'Next renewal',
    manageSubscription: 'Manage Subscription',
    noSubscription: 'You don\'t have an active subscription',
    orderDate: 'Date',
    orderTotal: 'Total',
    orderStatus: 'Status',
    delivered: 'Delivered',
    reorder: 'Reorder',
    
    audioExperience: 'Audio Experience',
    premiumContent: 'Premium Content',
    unlockAccess: 'Unlock Access',
    subscriptionPlans: 'Subscription Plans',
    monthly: 'Monthly',
    quarterly: 'Quarterly',
    yearly: 'Yearly',
    audioDescription: 'Complement your candle ritual with audio experiences designed to deepen your wellbeing. Each track has been carefully created to elevate your meditation and relaxation practice.',
    ambientMusic: 'Ambient Music',
    guidedMeditations: 'Guided Meditations',
    healingFrequencies: 'Healing Frequencies',
    exclusiveContent: 'Exclusive Content',
    freePreview: 'Free Preview',
    freePreviewDesc: 'Listen to samples of our most popular tracks',
    deepCalm: 'Deep Calm',
    spiritualConnection: 'Spiritual Connection',
    emotionalBalance: 'Emotional Balance',
    previewSample: '2-minute sample',
    listenPreview: 'Listen to Preview',
    chooseYourPlan: 'Choose Your Plan',
    planMonthly: 'Monthly',
    planQuarterly: 'Quarterly',
    planYearly: 'Yearly',
    perMonth: '/ month',
    per3Months: '/ 3 months',
    perYear: '/ year',
    save: 'Save',
    mostPopular: 'Most Popular',
    selectPlan: 'Select Plan',
    planFeature1: 'Full access to audio library',
    planFeature2: 'Weekly guided meditations',
    planFeature3: 'Premium ambient music',
    planFeature4: 'Healing frequencies',
    planFeature5: 'All monthly plan benefits',
    planFeature6: 'Exclusive quarterly content',
    planFeature7: 'Extended meditation sessions',
    planFeature8: 'Personalized playlists',
    planFeature9: 'All previous benefits',
    planFeature10: 'Access to exclusive masterclasses',
    planFeature11: 'Discounts on V&M products',
    planFeature12: 'Early access to content',
    uniqueKeyAccess: 'Unique Key Access',
    uniqueKeyAccessDesc: 'Enter your unique access key to unlock premium content',
    enterAccessKey: 'Enter your access key',
    unlock: 'Unlock',
    invalidKey: 'Invalid key',
    
    newsletter: 'Newsletter',
    subscribeNewsletter: 'Subscribe to our newsletter',
    newsletterDesc: 'Receive exclusive content, launches, and special offers',
    email: 'Email',
    send: 'Send',
    subscribing: 'Subscribing...',
    subscribed: 'Subscribed!',
    subscribedDesc: 'Thank you for subscribing to our newsletter.',
    
    welcomeBack: 'Welcome Back',
    loginDesc: 'Sign in to access your account',
    password: 'Password',
    rememberMe: 'Remember me',
    forgotPassword: 'Forgot your password?',
    noAccount: 'Don\'t have an account?',
    createAccount: 'Create Account',
    createAccountDesc: 'Join the V&M family',
    confirmPassword: 'Confirm Password',
    hasAccount: 'Already have an account?',
    
    loading: 'Loading...',
    search: 'Search',
    filter: 'Filter',
    sort: 'Sort',
    cancel: 'Cancel',
    delete: 'Delete',
    edit: 'Edit',
    hours: 'hours',
    back: 'Back',
    free: 'Free',
    freeShippingOver100: 'Free shipping on orders over $100!',
    quantityLabel: 'Quantity',

    // Footer - Information Section
    information: 'Information',
    contact: 'Contact',
    technicalSheet: 'Technical Sheet',
    termsOfUse: 'Terms of Use',
    privacyPolicy: 'Privacy Policy',

    // Subscription Page
    premiumAudioExperience: 'Premium Audio Experience',
    subscriptionHeaderDesc: 'Unlock unlimited access to our exclusive audio library with guided meditations, ambient soundscapes, and relaxation experiences.',
    activeSubscription: 'You have an active subscription',
    manageSubscriptionLink: 'Manage subscription',
    bestValue: 'Best Value',
    perPeriod: 'per',
    frequentlyAskedQuestions: 'Frequently Asked Questions',
    faqCancelTitle: 'Can I cancel anytime?',
    faqCancelAnswer: 'Yes! You can cancel your subscription at any time from your account settings. You\'ll continue to have access until the end of your current billing period.',
    faqChangePlanTitle: 'Can I change my plan?',
    faqChangePlanAnswer: 'Absolutely. You can upgrade or downgrade your plan at any time from your account settings. Changes will take effect at your next billing cycle.',
    faqPaymentTitle: 'What payment methods do you accept?',
    faqPaymentAnswer: 'We accept all major credit and debit cards through Transbank WebPay Plus, Chile\'s most trusted payment platform.',
    faqTrialTitle: 'Is there a free trial?',
    faqTrialAnswer: 'Currently, we don\'t offer a free trial, but you can preview selected audio experiences on our product pages before subscribing.',

    // Subscription Legal Acceptance
    beforeSubscribe: 'Before subscribing, please read and accept:',
    acceptTerms: 'I have read and accept the',
    acceptTermsSuffix: 'of the subscription system.',
    acceptPrivacy: 'I have read and accept the',
    acceptPrivacySuffix: 'of V&M Candle Experience.',
    mustAcceptBoth: '* You must accept both documents to subscribe.',
    canProceed: 'You can proceed with the subscription.',
    acceptTermsButton: 'Accept the terms',
    mustAcceptConditions: 'You must accept the conditions above',
    alreadySubscribed: 'Already subscribed',
    subscribeNow: 'Subscribe',
    processingPayment: 'Processing...',

    // Product Documentation Page
    productDocumentation: 'Product Documentation',
    productDocumentationDesc: 'Technical and safety information about our V&M Candle Experience products. Transparency and quality in every detail.',
    technicalDataSheet: 'Official Technical Data Sheet',
    safetyDataSheet: 'Safety Data Sheet – MSDS',
    safetyDataSheetSubtitle: 'Material Safety Data Sheet',
    issuedDate: 'Issue date',

    // Technical Sheet Sections
    productIdentification: 'Product Identification',
    productName: 'Product Name',
    brand: 'Brand',
    productType: 'Product Type',
    composition: 'Composition',
    naturalSoyWax: 'Natural Soy Wax',
    waxAmount: 'Wax Amount',
    essentialOil: 'Essential Oil',
    totalWeight: 'Total Weight',
    aromaticLoad: 'Aromatic Load',
    concentrationPercentage: 'Concentration percentage',
    highPerfumery: 'High Perfumery – Premium Edition',
    curingTime: 'Curing Time',
    minimumRecommended: 'Minimum Recommended',
    optimalLuxury: 'Optimal Luxury Level',
    days: 'days',
    wickType: 'Wick Type',
    cottonWick: '100% natural cotton wick',
    usageInstructions: 'Usage Instructions',
    usageStep1: 'Light the candle on a stable, heat-resistant surface.',
    usageStep2: 'Allow to scent the space for at least 45 minutes.',
    usageStep3: 'Do not leave lit for more than 2-3 hours continuously.',
    keepAwayFromChildren: 'Keep away from children and pets.',
    safetyWarnings: 'Safety Warnings',
    noFlammableMaterials: 'Do not use near flammable materials',
    noMoveWhileLit: 'Do not move the candle while lit',
    keepDistance: 'Keep at least 10 cm between lit candles',
    productClassification: 'Product Classification',
    classificationDesc: 'Premium aromatic product for environmental use.',
    notMedicine: 'Not a medicine.',
    manufacturing: 'Manufacturing',
    manufacturingDesc: 'Handcrafted product made in small batches under high-quality artisanal standards.',
    signatureLuxuryNote: 'Due to its high aromatic concentration, this product belongs to the Signature Luxury line of V&M Candle Experience and is intended for ritual, ceremonial, or high perfumery use.',

    // MSDS Sections
    hazardIdentification: 'Hazard Identification',
    flammableProduct: 'Flammable product',
    burnRisk: 'Risk of burns from hot wax',
    nonToxicNormal: 'Non-toxic under normal conditions of use',
    compositionInfo: 'Composition / Information on Ingredients',
    vegetableSoyWax: 'Vegetable soy wax',
    naturalFragrances: 'Natural fragrances',
    leadFreeCottonWick: 'Lead-free cotton wick',
    firstAid: 'First Aid Measures',
    skinContact: 'Skin contact:',
    coolWithWater: 'Cool with cold water.',
    fireFighting: 'Fire-Fighting Measures',
    useClassBExtinguisher: 'Use Class B extinguishers',
    neverUseWater: 'Never use water directly on burning wax',
    spillMeasures: 'Accidental Release Measures',
    letSolidify: 'Let the wax solidify before cleaning',
    avoidBurns: 'Avoid burns',
    handlingStorage: 'Handling and Storage',
    keepFromHeat: 'Keep away from intense heat',
    storeCoolDry: 'Store in a cool, dry place',
    exposureControl: 'Exposure Controls / Personal Protection',
    noSpecialProtection: 'No special protection required under normal use.',
    physicalProperties: 'Physical and Chemical Properties',
    state: 'State',
    solid: 'Solid',
    color: 'Color',
    variable: 'Variable',
    smell: 'Odor',
    aromatic: 'Aromatic',
    stabilityReactivity: 'Stability and Reactivity',
    stableProduct: 'Stable product under normal conditions',
    avoidDirectFire: 'Avoid direct fire exposure',
    toxicologicalInfo: 'Toxicological Information',
    nonToxic: 'Non-toxic',
    doNotIngest: 'Do not ingest',
    ecologicalInfo: 'Ecological Information',
    biodegradable: 'Biodegradable product',
    recyclablePackaging: 'Recyclable packaging',
    disposalInfo: 'Disposal Considerations',
    disposeLocally: 'Dispose of according to local regulations',
    noDrainDisposal: 'Do not pour into drains',
    transportInfo: 'Transport Information',
    notDangerous: 'Not considered hazardous material for ground transport.',
    regulatoryInfo: 'Regulatory Information',
    chileanCompliance: 'Product compliant with current Chilean regulations for decorative objects.',
    otherInfo: 'Other Information',
    infoDisclaimer: 'This document has been prepared for informational and preventive safety purposes.',
    emergencyPhone: 'Emergency',
    contactQuestions: 'For additional inquiries, contact',

    // Terms of Use Page
    termsTitle: 'TERMS OF USE – SUBSCRIPTION SYSTEM',
    termsLastUpdate: 'Last updated',
    termsIntro: 'By subscribing to V&M Candle Experience, the user fully accepts the following Terms of Use:',
    termsSection1Title: '1. PURPOSE OF SERVICE',
    termsSection1Content: 'The subscription grants access to digital content, programs, sessions, educational material, audio, videos, courses, mentoring, or other services offered on the platform, according to the subscribed plan.',
    termsSection2Title: '2. NATURE OF SERVICE',
    termsSection2Content: 'All content offered is educational, formative, complementary therapeutic, and personal development in nature, and does NOT replace medical, psychological, or psychiatric treatments.',
    termsSection2Note: 'The user is fully responsible for the use of the information provided.',
    termsSection3Title: '3. PAYMENT METHOD',
    termsSection4Title: '4. NO REFUND POLICY',
    termsSection4Intro: 'Once the subscription payment is made:',
    termsSection4NoRefund: 'NO refunds are made, total or partial.',
    termsSection4Cancel: 'The user may cancel their subscription to avoid future charges, but the already paid period is not refunded.',
    termsSection5Title: '5. CANCELLATION',
    termsSection5Intro: 'The user may cancel their subscription at any time from their account or by requesting via email to:',
    termsSection5Effect: 'Cancellation:',
    termsSection5Stop: 'Stops future charges.',
    termsSection5Access: 'Maintains active access until the end date of the already paid period.',
    termsSection6Title: '6. ACCOUNT ACCESS AND USE',
    termsSection7Title: '7. INTELLECTUAL PROPERTY',
    termsSection7Content: 'All platform content is the exclusive property of V&M Candle Experience.',
    termsSection7Forbidden: 'It is strictly prohibited to:',
    termsSection7Auth: 'without express written authorization.',
    termsSection8Title: '8. SERVICE MODIFICATIONS',
    termsSection8Intro: 'The platform reserves the right to:',
    termsSection8Note: 'without negatively affecting the user\'s contracted access.',
    termsSection9Title: '9. USER RESPONSIBILITY',
    termsSection9Intro: 'The user declares that:',
    termsSection10Title: '10. SERVICE SUSPENSION OR TERMINATION',
    termsSection10Intro: 'We reserve the right to suspend an account if the user:',
    termsSection11Title: '11. DATA PROTECTION',
    termsSection11Content: 'User data will be treated with strict confidentiality and in accordance with current data protection legislation.',
    termsSection12Title: '12. JURISDICTION',
    termsSection12Content: 'These conditions are governed by the laws of the Republic of Chile. Any conflict will be resolved in the competent courts of Santiago.',
    termsSection13Title: '13. ACCEPTANCE',
    termsSection13Content: 'By subscribing, the user declares to have read, understood, and fully accepted these Terms of Use.',

    // Privacy Policy Page
    privacyTitle: 'PRIVACY POLICY',
    privacyIntro: 'At V&M Candle Experience, we respect and protect the privacy of all our users. This Privacy Policy describes how we collect, use, and protect your personal data.',
    privacyAcceptance: 'By using our services, you accept the practices described below.',
    privacySection1Title: '1. DATA CONTROLLER',
    privacySection1Intro: 'The data controller is:',
    privacyName: 'Name',
    privacyBrand: 'Trade name',
    privacyContact: 'Contact email',
    privacyCountry: 'Country',
    privacySection2Title: '2. PERSONAL DATA WE COLLECT',
    privacySection2Intro: 'We may collect the following data:',
    privacySection2Note: 'We never request unnecessary sensitive data.',
    privacySection3Title: '3. PURPOSE OF DATA USE',
    privacySection3Intro: 'Your personal data is used for:',
    privacySection4Title: '4. CONFIDENTIALITY AND SECURITY',
    privacySection4Content: 'Your data is stored under strict security and confidentiality measures. We implement technological and administrative protocols to prevent unauthorized access, loss, or alteration of information.',
    privacySection5Title: '5. USE OF PAYMENT PLATFORMS AND THIRD PARTIES',
    privacySection5Intro: 'Our payments may be processed through external platforms such as:',
    privacySection5Note: 'These platforms have their own privacy policies and data handling practices.',
    privacySection6Title: '6. USE OF COOKIES',
    privacySection6Intro: 'Our site may use cookies to:',
    privacySection6Note: 'Users can configure their browser to reject cookies if desired.',
    privacySection7Title: '7. USER RIGHTS',
    privacySection7Intro: 'The user has the right to:',
    privacySection7Contact: 'To exercise these rights, you may write to:',
    privacySection8Title: '8. DATA RETENTION',
    privacySection8Content: 'Data will be retained for the time necessary to fulfill the purposes for which it was collected or by legal obligation.',
    privacySection9Title: '9. MINORS',
    privacySection9Content: 'Our services are not intended for persons under 18 years of age. If we detect use by a minor without authorization, the data will be deleted immediately.',
    privacySection10Title: '10. POLICY MODIFICATIONS',
    privacySection10Content: 'We reserve the right to modify this Privacy Policy at any time. Changes will be published in this same section.',
    privacySection11Title: '11. ACCEPTANCE',
    privacySection11Content: 'Use of the platform implies express acceptance of this Privacy Policy.',
    privacySection12Title: '12. APPLICABLE LEGISLATION',
    privacySection12Content: 'This policy is governed by the current legislation of the Republic of Chile, especially Law No. 19,628 on personal data protection.',
  },
  fr: {
    ...productTranslations.fr,
    home: 'Accueil',
    shop: 'Boutique',
    audio: 'Audio Premium',
    account: 'Compte',
    cart: 'Panier',
    login: 'Connexion',
    register: "S'inscrire",
    logout: 'Déconnexion',
    
    heroTitle: 'V&M Candle Experience',
    heroSubtitle: 'Rituels qui Restaurent votre Âme',
    heroDescription: 'Bougies artisanales haut de gamme, formulées avec des cires végétales, des huiles essentielles pures et des fragrances de qualité parfumerie.',
    shopNow: 'Acheter Maintenant',
    subscribe: "S'abonner",
    exploreAudio: 'Explorer Audio Premium',
    
    products: 'Produits',
    addToCart: 'Ajouter au Panier',
    viewDetails: 'Voir Détails',
    price: 'Prix',
    inStock: 'En Stock',
    outOfStock: 'Épuisé',
    
    yourCart: 'Votre Panier',
    subtotal: 'Sous-total',
    shipping: 'Livraison',
    total: 'Total',
    checkout: 'Commander',
    continueShopping: 'Continuer les Achats',
    emptyCart: 'Votre panier est vide',
    
    myAccount: 'Mon Compte',
    orderHistory: 'Historique des Commandes',
    quickBuy: 'Achat Rapide',
    subscription: 'Abonnement',
    profile: 'Profil',
    
    audioExperience: 'Expérience Audio',
    premiumContent: 'Contenu Premium',
    unlockAccess: 'Débloquer Accès',
    subscriptionPlans: "Plans d'Abonnement",
    monthly: 'Mensuel',
    quarterly: 'Trimestriel',
    yearly: 'Annuel',
    
    newsletter: 'Newsletter',
    subscribeNewsletter: 'Abonnez-vous à notre newsletter',
    email: 'Email',
    send: 'Envoyer',
    
    loading: 'Chargement...',
    search: 'Rechercher',
    filter: 'Filtrer',
    sort: 'Trier',
    cancel: 'Annuler',
    save: 'Enregistrer',
    delete: 'Supprimer',
    edit: 'Modifier',
  },
  de: {
    ...productTranslations.de,
    home: 'Startseite',
    shop: 'Shop',
    audio: 'Premium Audio',
    account: 'Konto',
    cart: 'Warenkorb',
    login: 'Anmelden',
    register: 'Registrieren',
    logout: 'Abmelden',
    
    heroTitle: 'V&M Candle Experience',
    heroSubtitle: 'Rituale, die Ihre Seele Wiederherstellen',
    heroDescription: 'Hochwertige handwerkliche Kerzen, formuliert mit pflanzlichen Wachsen, reinen ätherischen Ölen und Parfümqualität Düften.',
    shopNow: 'Jetzt Einkaufen',
    subscribe: 'Abonnieren',
    exploreAudio: 'Premium Audio Erkunden',
    
    products: 'Produkte',
    addToCart: 'In den Warenkorb',
    viewDetails: 'Details Anzeigen',
    price: 'Preis',
    inStock: 'Auf Lager',
    outOfStock: 'Ausverkauft',
    
    yourCart: 'Ihr Warenkorb',
    subtotal: 'Zwischensumme',
    shipping: 'Versand',
    total: 'Gesamt',
    checkout: 'Zur Kasse',
    continueShopping: 'Weiter Einkaufen',
    emptyCart: 'Ihr Warenkorb ist leer',
    
    myAccount: 'Mein Konto',
    orderHistory: 'Bestellverlauf',
    quickBuy: 'Schnellkauf',
    subscription: 'Abonnement',
    profile: 'Profil',
    
    audioExperience: 'Audio Erlebnis',
    premiumContent: 'Premium Inhalt',
    unlockAccess: 'Zugang Freischalten',
    subscriptionPlans: 'Abonnement-Pläne',
    monthly: 'Monatlich',
    quarterly: 'Vierteljährlich',
    yearly: 'Jährlich',
    
    newsletter: 'Newsletter',
    subscribeNewsletter: 'Abonnieren Sie unseren Newsletter',
    email: 'E-Mail',
    send: 'Senden',
    
    loading: 'Lädt...',
    search: 'Suchen',
    filter: 'Filtern',
    sort: 'Sortieren',
    cancel: 'Abbrechen',
    save: 'Speichern',
    delete: 'Löschen',
    edit: 'Bearbeiten',
  },
  pt: {
    ...productTranslations.pt,
    home: 'Início',
    shop: 'Loja',
    audio: 'Áudio Premium',
    account: 'Conta',
    cart: 'Carrinho',
    login: 'Entrar',
    register: 'Registrar',
    logout: 'Sair',
    
    heroTitle: 'V&M Candle Experience',
    heroSubtitle: 'Rituais que Restauram sua Alma',
    heroDescription: 'Velas artesanais de alta qualidade, formuladas com ceras vegetais, óleos essenciais puros e fragrâncias de grau perfumista.',
    shopNow: 'Comprar Agora',
    subscribe: 'Inscrever-se',
    exploreAudio: 'Explorar Áudio Premium',
    
    products: 'Produtos',
    addToCart: 'Adicionar ao Carrinho',
    viewDetails: 'Ver Detalhes',
    price: 'Preço',
    inStock: 'Em Estoque',
    outOfStock: 'Esgotado',
    
    yourCart: 'Seu Carrinho',
    subtotal: 'Subtotal',
    shipping: 'Envio',
    total: 'Total',
    checkout: 'Finalizar Compra',
    continueShopping: 'Continuar Comprando',
    emptyCart: 'Seu carrinho está vazio',
    
    myAccount: 'Minha Conta',
    orderHistory: 'Histórico de Pedidos',
    quickBuy: 'Compra Rápida',
    subscription: 'Assinatura',
    profile: 'Perfil',
    
    audioExperience: 'Experiência de Áudio',
    premiumContent: 'Conteúdo Premium',
    unlockAccess: 'Desbloquear Acesso',
    subscriptionPlans: 'Planos de Assinatura',
    monthly: 'Mensal',
    quarterly: 'Trimestral',
    yearly: 'Anual',
    
    newsletter: 'Boletim',
    subscribeNewsletter: 'Inscreva-se em nossa newsletter',
    email: 'Email',
    send: 'Enviar',
    
    loading: 'Carregando...',
    search: 'Pesquisar',
    filter: 'Filtrar',
    sort: 'Ordenar',
    cancel: 'Cancelar',
    save: 'Salvar',
    delete: 'Excluir',
    edit: 'Editar',
  },
  hi: {
    ...productTranslations.hi,
    home: 'होम',
    shop: 'दुकान',
    audio: 'प्रीमियम ऑडियो',
    account: 'खाता',
    cart: 'कार्ट',
    login: 'लॉग इन करें',
    register: 'रजिस्टर',
    logout: 'लॉग आउट',
    
    heroTitle: 'V&M Candle Experience',
    heroSubtitle: 'अनुष्ठान जो आपकी आत्मा को पुनर्स्थापित करते हैं',
    heroDescription: 'उच्च अंत शिल्पकार मोमबत्तियाँ, पौधे-आधारित मोम, शुद्ध आवश्यक तेल और इत्र-ग्रेड सुगंध के साथ तैयार की गई।',
    shopNow: 'अभी खरीदें',
    subscribe: 'सब्सक्राइब करें',
    exploreAudio: 'प्रीमियम ऑडियो एक्सप्लोर करें',
    
    products: 'उत्पाद',
    addToCart: 'कार्ट में जोड़ें',
    viewDetails: 'विवरण देखें',
    price: 'मूल्य',
    inStock: 'स्टॉक में',
    outOfStock: 'स्टॉक से बाहर',
    
    yourCart: 'आपका कार्ट',
    subtotal: 'उप-योग',
    shipping: 'शिपिंग',
    total: 'कुल',
    checkout: 'चेकआउट',
    continueShopping: 'खरीदारी जारी रखें',
    emptyCart: 'आपका कार्ट खाली है',
    
    myAccount: 'मेरा खाता',
    orderHistory: 'ऑर्डर इतिहास',
    quickBuy: 'त्वरित खरीद',
    subscription: 'सदस्यता',
    profile: 'प्रोफ़ाइल',
    
    audioExperience: 'ऑडियो अनुभव',
    premiumContent: 'प्रीमियम सामग्री',
    unlockAccess: 'पहुंच अनलॉक करें',
    subscriptionPlans: 'सदस्यता योजनाएं',
    monthly: 'मासिक',
    quarterly: 'त्रैमासिक',
    yearly: 'वार्षिक',
    
    newsletter: 'न्यूज़लेटर',
    subscribeNewsletter: 'हमारे न्यूज़लेटर की सदस्यता लें',
    email: 'ईमेल',
    send: 'भेजें',
    
    loading: 'लोड हो रहा है...',
    search: 'खोजें',
    filter: 'फ़िल्टर',
    sort: 'क्रमबद्ध करें',
    cancel: 'रद्द करें',
    save: 'सेव करें',
    delete: 'हटाएं',
    edit: 'संपादित करें',
  },
  zh: {
    ...productTranslations.zh,
    home: '首页',
    shop: '商店',
    audio: '高级音频',
    account: '账户',
    cart: '购物车',
    login: '登录',
    register: '注册',
    logout: '退出',
    
    heroTitle: 'V&M 蜡烛体验',
    heroSubtitle: '恢复灵魂的仪式',
    heroDescription: '高端手工蜡烛，采用植物蜡、纯精油和香水级香料配制而成。',
    shopNow: '立即购买',
    subscribe: '订阅',
    exploreAudio: '探索高级音频',
    
    products: '产品',
    addToCart: '添加到购物车',
    viewDetails: '查看详情',
    price: '价格',
    inStock: '有货',
    outOfStock: '缺货',
    
    yourCart: '您的购物车',
    subtotal: '小计',
    shipping: '运费',
    total: '总计',
    checkout: '结账',
    continueShopping: '继续购物',
    emptyCart: '您的购物车是空的',
    
    myAccount: '我的账户',
    orderHistory: '订单历史',
    quickBuy: '快速购买',
    subscription: '订阅',
    profile: '个人资料',
    
    audioExperience: '音频体验',
    premiumContent: '高级内容',
    unlockAccess: '解锁访问',
    subscriptionPlans: '订阅计划',
    monthly: '每月',
    quarterly: '每季度',
    yearly: '每年',
    
    newsletter: '通讯',
    subscribeNewsletter: '订阅我们的通讯',
    email: '电子邮件',
    send: '发送',
    
    loading: '加载中...',
    search: '搜索',
    filter: '筛选',
    sort: '排序',
    cancel: '取消',
    save: '保存',
    delete: '删除',
    edit: '编辑',
  },
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider = ({ children }: { children: ReactNode }) => {
  const [language, setLanguage] = useState<Language>('es');

  const t = (key: string): string => {
    const allTranslations = {
      ...translations[language],
      ...productTranslations[language],
      ...commonTranslations[language],
    };
    return allTranslations[key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
